/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import Morfolojik.Morfolojik;
import Filtreleme.Filtre;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import Onİslem.RGBBlue;
import Onİslem.RGBGreen;
import Onİslem.RGBred;
import Onİslem.Önİslem;
import Segmentasoyon.Segmentasyon;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageOutputStream;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Arda
 */
public class NewJFrame extends javax.swing.JFrame {

    private BufferedImage OrjinalResim;

    BufferedImage SonResim;
    private boolean KesmeAktif = false;
    ImageIcon icon;
    //Crop crop;

    public NewJFrame() {
        initComponents();

        ZoomİnButton.setVisible(false);
        ZoomOutButton.setVisible(false);

    }
    Filtre filtre;
    Önİslem önislem;
    Morfolojik morfolojik;
    ButtonGroup group1 = new ButtonGroup();
    ButtonGroup group2 = new ButtonGroup();
    ButtonGroup group3 = new ButtonGroup();
    ButtonGroup group4 = new ButtonGroup();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        Xtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        YText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ResimScrollPane = new javax.swing.JScrollPane();
        ZoomİnButton = new javax.swing.JButton();
        ZoomOutButton = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        ÖnİslemMenü = new javax.swing.JMenu();
        ÖnİslemRadio = new javax.swing.JCheckBoxMenuItem();
        Önİslem1İtem = new javax.swing.JMenuItem();
        Önİslem2İtem = new javax.swing.JMenuItem();
        Önİslem3İtem = new javax.swing.JMenuItem();
        Önİslem4İtem = new javax.swing.JMenuItem();
        Önİslem5İtem = new javax.swing.JMenuItem();
        FiltreMenü = new javax.swing.JMenu();
        FiltreRadio = new javax.swing.JCheckBoxMenuItem();
        Filtre1İtem = new javax.swing.JMenuItem();
        Filtre2İtem = new javax.swing.JMenuItem();
        Filtre3İtem = new javax.swing.JMenuItem();
        Filtre4İtem = new javax.swing.JMenuItem();
        Filtre5İtem = new javax.swing.JMenuItem();
        MorfoMenü = new javax.swing.JMenu();
        MorfoRadio = new javax.swing.JCheckBoxMenuItem();
        Morfo1İtem = new javax.swing.JMenuItem();
        Morfo2İtem = new javax.swing.JMenuItem();
        Morfo3İtem = new javax.swing.JMenuItem();
        Morfo4İtem = new javax.swing.JMenuItem();
        SegmentMenü = new javax.swing.JMenu();
        SegmensatyonRadio = new javax.swing.JCheckBoxMenuItem();
        Segme1İtem = new javax.swing.JMenuItem();
        Segme2İtem = new javax.swing.JMenuItem();
        Segme3İtem = new javax.swing.JMenuItem();
        Segme4İtem = new javax.swing.JMenuItem();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBounds(new java.awt.Rectangle(50, 50, 300, 150));
        jDialog1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog1.setLocation(new java.awt.Point(250, 250));

        jLabel1.setText("Genişlik(X):");

        jLabel2.setText("Yükseklik(Y):");

        jButton1.setText("Uygula");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Xtext)
                    .addComponent(YText, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Xtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(YText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ResimScrollPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ResimScrollPaneMouseDragged(evt);
            }
        });
        ResimScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ResimScrollPaneMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ResimScrollPaneMouseReleased(evt);
            }
        });

        ZoomİnButton.setText("+");
        ZoomİnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomİnButtonActionPerformed(evt);
            }
        });

        ZoomOutButton.setText("-");
        ZoomOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomOutButtonActionPerformed(evt);
            }
        });

        jMenu4.setText("Dosya");

        jMenuItem2.setText("Resim Aç");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu1.setText("Kaydet");

        jMenuItem1.setText("JPG");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("BMP");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("TIF");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("PNG");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenu4.add(jMenu1);

        jMenuBar2.add(jMenu4);

        ÖnİslemMenü.setText("Ön İşlem");
        ÖnİslemMenü.setEnabled(false);
        ÖnİslemMenü.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                ÖnİslemMenüMenuSelected(evt);
            }
        });

        ÖnİslemRadio.setSelected(true);
        ÖnİslemRadio.setText("Önİşlem Uygulamak İstemiyorum");
        ÖnİslemMenü.add(ÖnİslemRadio);

        Önİslem1İtem.setText("Renkli resmi gri seviye dönüştürme");
        Önİslem1İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Önİslem1İtemActionPerformed(evt);
            }
        });
        ÖnİslemMenü.add(Önİslem1İtem);

        Önİslem2İtem.setText("Resim büyültme, küçültme");
        Önİslem2İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Önİslem2İtemActionPerformed(evt);
            }
        });
        ÖnİslemMenü.add(Önİslem2İtem);

        Önİslem3İtem.setText("Resmi yeniden boyutlandırma");
        Önİslem3İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Önİslem3İtemActionPerformed(evt);
            }
        });
        ÖnİslemMenü.add(Önİslem3İtem);

        Önİslem4İtem.setText("Resimden istenilen bölgenin kesilip alınması");
        Önİslem4İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Önİslem4İtemActionPerformed(evt);
            }
        });
        ÖnİslemMenü.add(Önİslem4İtem);

        Önİslem5İtem.setText("Histogram oluşturma");
        Önİslem5İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Önİslem5İtemActionPerformed(evt);
            }
        });
        ÖnİslemMenü.add(Önİslem5İtem);

        jMenuBar2.add(ÖnİslemMenü);

        FiltreMenü.setText("Filtreleme");
        FiltreMenü.setEnabled(false);
        FiltreMenü.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                FiltreMenüMenuSelected(evt);
            }
        });

        FiltreRadio.setSelected(true);
        FiltreRadio.setText("Filtreleme Uygulama İstemiyorum");
        FiltreMenü.add(FiltreRadio);

        Filtre1İtem.setText("Bulanıklaştırma filtresi");
        Filtre1İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtre1İtemActionPerformed(evt);
            }
        });
        FiltreMenü.add(Filtre1İtem);

        Filtre2İtem.setText("Keskinleştirme filtresi");
        Filtre2İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtre2İtemActionPerformed(evt);
            }
        });
        FiltreMenü.add(Filtre2İtem);

        Filtre3İtem.setText("Ortanca filtresi");
        Filtre3İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtre3İtemActionPerformed(evt);
            }
        });
        FiltreMenü.add(Filtre3İtem);

        Filtre4İtem.setText("Laplace filtresi ");
        Filtre4İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtre4İtemActionPerformed(evt);
            }
        });
        FiltreMenü.add(Filtre4İtem);

        Filtre5İtem.setText("Kenar bulma filtresi ");
        Filtre5İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtre5İtemActionPerformed(evt);
            }
        });
        FiltreMenü.add(Filtre5İtem);

        jMenuBar2.add(FiltreMenü);

        MorfoMenü.setText("Morfolojik İşlem");
        MorfoMenü.setEnabled(false);
        MorfoMenü.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MorfoMenüMenuSelected(evt);
            }
        });

        MorfoRadio.setSelected(true);
        MorfoRadio.setText("Morfolojik İşlem Uygulamak İstemiyorum");
        MorfoMenü.add(MorfoRadio);

        Morfo1İtem.setText("Siyah beyaz resimde genişletme");
        Morfo1İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Morfo1İtemActionPerformed(evt);
            }
        });
        MorfoMenü.add(Morfo1İtem);

        Morfo2İtem.setText("Siyah beyaz resimde erozyon");
        Morfo2İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Morfo2İtemActionPerformed(evt);
            }
        });
        MorfoMenü.add(Morfo2İtem);

        Morfo3İtem.setText("Siyah beyaz resimde açma");
        Morfo3İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Morfo3İtemActionPerformed(evt);
            }
        });
        MorfoMenü.add(Morfo3İtem);

        Morfo4İtem.setText("Siyah beyaz resimde kapama");
        Morfo4İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Morfo4İtemActionPerformed(evt);
            }
        });
        MorfoMenü.add(Morfo4İtem);

        jMenuBar2.add(MorfoMenü);

        SegmentMenü.setText("Segmentasyon");
        SegmentMenü.setEnabled(false);
        SegmentMenü.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                SegmentMenüMenuSelected(evt);
            }
        });

        SegmensatyonRadio.setSelected(true);
        SegmensatyonRadio.setText("Segmentasyon Uygulamak İstemiyorum");
        SegmentMenü.add(SegmensatyonRadio);

        Segme1İtem.setText("Gri seviye resimde eşik değeri bulma");
        Segme1İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Segme1İtemActionPerformed(evt);
            }
        });
        SegmentMenü.add(Segme1İtem);

        Segme2İtem.setText("Siyah beyaz resimde 4’lü komşuluk ile nesne bulma ve gösterme");
        Segme2İtem.setToolTipText("");
        Segme2İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Segme2İtemActionPerformed(evt);
            }
        });
        SegmentMenü.add(Segme2İtem);

        Segme3İtem.setText("Gri seviye resimde istenilen bir yöntemle nesne bulma ve gösterme");
        Segme3İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Segme3İtemActionPerformed(evt);
            }
        });
        SegmentMenü.add(Segme3İtem);

        Segme4İtem.setText("Renkli resimde istenilen bir yöntemle nesne bulma ve gösterme");
        Segme4İtem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Segme4İtemActionPerformed(evt);
            }
        });
        SegmentMenü.add(Segme4İtem);

        jMenuBar2.add(SegmentMenü);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ZoomİnButton)
                .addGap(18, 18, 18)
                .addComponent(ZoomOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(ResimScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ResimScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZoomİnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZoomOutButton))
                .addGap(18, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
JLabel resimLabel = new JLabel();

    private Image Zoomİn(int w, int h, Image img) {
        BufferedImage bımg = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D grp = bımg.createGraphics();
        grp.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        grp.drawImage(img, 0, 0, w, h, null);
        grp.dispose();
        return bımg;
    }

    private Image ZoomOut(int w, int h, Image img) {
        BufferedImage bımg = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D grp = bımg.createGraphics();
        grp.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        grp.drawImage(img, 0, 0, w, h, null);

        grp.dispose();
        return bımg;
    }

    private void ZoomİnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomİnButtonActionPerformed
        int w = resimLabel.getWidth();
        int h = resimLabel.getHeight();
        ImageIcon icon = new ImageIcon(Zoomİn(w + 100, h + 100, SonResim));
        resimLabel.setIcon(icon);
    }//GEN-LAST:event_ZoomİnButtonActionPerformed

    private void ZoomOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomOutButtonActionPerformed
        int w = resimLabel.getWidth();
        int h = resimLabel.getHeight();
        ImageIcon icon = new ImageIcon(ZoomOut(w - 100, h - 100, SonResim));
        resimLabel.setIcon(icon);

    }//GEN-LAST:event_ZoomOutButtonActionPerformed
    /**/
    private void ResimScrollPaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResimScrollPaneMouseDragged
        if (KesmeAktif) {
            repaint();
            önislem.setDrag_status(1);

            önislem.setX2(evt.getXOnScreen());
            önislem.setY2(evt.getYOnScreen());
        }

    }//GEN-LAST:event_ResimScrollPaneMouseDragged

    private void ResimScrollPaneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResimScrollPaneMouseReleased
        if (KesmeAktif) {
            repaint();
            if (önislem.getDrag_status() == 1) {
                önislem.setX2(evt.getXOnScreen());
                önislem.setY2(evt.getYOnScreen());
                try {
                    önislem.draggedScreen();
                    resimLabel.setIcon(new ImageIcon(önislem.draggedScreen()));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            KesmeAktif = false;
            SonResim = önislem.getSonuçResmi();
        }


    }//GEN-LAST:event_ResimScrollPaneMouseReleased

    private void ResimScrollPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResimScrollPaneMousePressed
        if (KesmeAktif) {
            repaint();
            önislem.setX1(evt.getXOnScreen());
            önislem.setY1(evt.getYOnScreen());
        }

    }//GEN-LAST:event_ResimScrollPaneMousePressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileFilter imageFilter = new FileNameExtensionFilter(
                "Image files", ImageIO.getReaderFileSuffixes());
        // FileFilter filter = new FileNameExtensionFilter("resim", "jpg", "png", "bmp", "tif");
        fileChooser.setFileFilter(imageFilter);

        OrjinalResim = null;

        if (fileChooser.showOpenDialog(jMenuItem2) == JFileChooser.APPROVE_OPTION) {
            try {
                OrjinalResim = ImageIO.read(fileChooser.getSelectedFile());

            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            resimLabel.setIcon(new ImageIcon(OrjinalResim));
            SonResim = OrjinalResim;

            //   jlab.setHorizontalAlignment(JLabel.CENTER);
            ResimScrollPane.getViewport().add(resimLabel);
            //       ResimScrollPane.setBounds(ResimScrollPane.getX(), ResimScrollPane.getY(), OrjinalResim.getWidth(), OrjinalResim.getHeight());

            önislem = new Önİslem(OrjinalResim);
            filtre = new Filtre(OrjinalResim);
            morfolojik = new Morfolojik(OrjinalResim);
            if (OrjinalResim != null) {
                ÖnİslemMenü.setEnabled(true);
                FiltreMenü.setEnabled(true);
                MorfoMenü.setEnabled(true);
                SegmentMenü.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void Önİslem1İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Önİslem1İtemActionPerformed
        önislem = new Önİslem(SonResim);
        resimLabel.setIcon(new ImageIcon(önislem.GriyeCevir()));
        SonResim = önislem.getSonuçResmi();

    }//GEN-LAST:event_Önİslem1İtemActionPerformed

    private void Filtre1İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtre1İtemActionPerformed

        filtre = new Filtre(SonResim);
        resimLabel.setIcon(new ImageIcon(filtre.Blur()));
        SonResim = filtre.getSonuçResmi();
    }//GEN-LAST:event_Filtre1İtemActionPerformed

    private void Filtre2İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtre2İtemActionPerformed

        filtre = new Filtre(SonResim);
        resimLabel.setIcon(new ImageIcon(filtre.Keskinleştirme()));
        SonResim = filtre.getSonuçResmi();

    }//GEN-LAST:event_Filtre2İtemActionPerformed

    private void Filtre3İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtre3İtemActionPerformed

        filtre = new Filtre(SonResim);
        resimLabel.setIcon(new ImageIcon(filtre.OrtaSon()));
        SonResim = filtre.getSonuçResmi();

    }//GEN-LAST:event_Filtre3İtemActionPerformed

    private void Filtre4İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtre4İtemActionPerformed

        filtre = new Filtre(SonResim);
        resimLabel.setIcon(new ImageIcon(filtre.laplace()));
        SonResim = filtre.getSonuçResmi();

    }//GEN-LAST:event_Filtre4İtemActionPerformed

    private void Filtre5İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtre5İtemActionPerformed

        filtre = new Filtre(SonResim);
        resimLabel.setIcon(new ImageIcon(filtre.kenar()));
        SonResim = filtre.getSonuçResmi();

    }//GEN-LAST:event_Filtre5İtemActionPerformed

    private void Önİslem5İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Önİslem5İtemActionPerformed
        önislem = new Önİslem(SonResim);
        önislem.RBGHistogram();
    }//GEN-LAST:event_Önİslem5İtemActionPerformed

    private void Önİslem2İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Önİslem2İtemActionPerformed
        önislem = new Önİslem(SonResim);
        ZoomİnButton.setVisible(true);
        ZoomOutButton.setVisible(true);
    }//GEN-LAST:event_Önİslem2İtemActionPerformed

    private void Önİslem4İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Önİslem4İtemActionPerformed
        KesmeAktif = true;
    }//GEN-LAST:event_Önİslem4İtemActionPerformed

    private void Morfo1İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Morfo1İtemActionPerformed
        int[] mask = {0, 1, 0, 1, 1, 1, 0, 1, 0};

        morfolojik = new Morfolojik(SonResim);
        resimLabel.setIcon(new ImageIcon(morfolojik.Genişletme(SonResim, mask, 3)));
        SonResim = morfolojik.getSonuçResmi();
    }//GEN-LAST:event_Morfo1İtemActionPerformed

    private void Morfo2İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Morfo2İtemActionPerformed

        int[] mask = {0, 1, 0, 1, 1, 1, 0, 1, 0};

        morfolojik = new Morfolojik(SonResim);
        resimLabel.setIcon(new ImageIcon(morfolojik.Erezyon(SonResim, mask, 3)));
        SonResim = morfolojik.getSonuçResmi();
    }//GEN-LAST:event_Morfo2İtemActionPerformed

    private void ÖnİslemMenüMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_ÖnİslemMenüMenuSelected
        if (ÖnİslemRadio.isSelected()) {
            Önİslem1İtem.setEnabled(false);
            Önİslem2İtem.setEnabled(false);
            Önİslem3İtem.setEnabled(false);
            Önİslem4İtem.setEnabled(false);
            Önİslem5İtem.setEnabled(false);
        } else {
            Önİslem1İtem.setEnabled(true);
            Önİslem2İtem.setEnabled(true);
            Önİslem3İtem.setEnabled(true);
            Önİslem4İtem.setEnabled(true);
            Önİslem5İtem.setEnabled(true);
        }
    }//GEN-LAST:event_ÖnİslemMenüMenuSelected

    private void FiltreMenüMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_FiltreMenüMenuSelected
        if (FiltreRadio.isSelected()) {
            Filtre1İtem.setEnabled(false);
            Filtre2İtem.setEnabled(false);
            Filtre3İtem.setEnabled(false);
            Filtre4İtem.setEnabled(false);
            Filtre5İtem.setEnabled(false);
        } else {
            Filtre1İtem.setEnabled(true);
            Filtre2İtem.setEnabled(true);
            Filtre3İtem.setEnabled(true);
            Filtre4İtem.setEnabled(true);
            Filtre5İtem.setEnabled(true);
        }
    }//GEN-LAST:event_FiltreMenüMenuSelected

    private void MorfoMenüMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MorfoMenüMenuSelected
        if (MorfoRadio.isSelected()) {
            Morfo1İtem.setEnabled(false);
            Morfo2İtem.setEnabled(false);
            Morfo3İtem.setEnabled(false);
            Morfo4İtem.setEnabled(false);
        } else {
            Morfo1İtem.setEnabled(true);
            Morfo2İtem.setEnabled(true);
            Morfo3İtem.setEnabled(true);
            Morfo4İtem.setEnabled(true);
        }
    }//GEN-LAST:event_MorfoMenüMenuSelected

    private void SegmentMenüMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_SegmentMenüMenuSelected
        if (SegmensatyonRadio.isSelected()) {
            Segme1İtem.setEnabled(false);
            Segme2İtem.setEnabled(false);
            Segme3İtem.setEnabled(false);
            Segme4İtem.setEnabled(false);
        } else {
            Segme1İtem.setEnabled(true);
            Segme2İtem.setEnabled(true);
            Segme3İtem.setEnabled(true);
            Segme4İtem.setEnabled(true);
        }
    }//GEN-LAST:event_SegmentMenüMenuSelected

    private void Önİslem3İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Önİslem3İtemActionPerformed
        jDialog1.setVisible(true);
        jDialog1.setTitle("Yeniden Boyutlandırma");
        //   jDialog1.setBounds(500, 500, 200, 504);
    }//GEN-LAST:event_Önİslem3İtemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            önislem = new Önİslem(SonResim);
            resimLabel.setIcon(new ImageIcon(önislem.YenidenBoyutlandır(Integer.parseInt(Xtext.getText()), Integer.parseInt(YText.getText()))));
            SonResim = önislem.getSonuçResmi();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialog1.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Morfo3İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Morfo3İtemActionPerformed
        int[] mask = {0, 1, 0, 1, 1, 1, 0, 1, 0};

        morfolojik = new Morfolojik(SonResim);
        resimLabel.setIcon(new ImageIcon(morfolojik.Openin(mask, 3)));
        SonResim = morfolojik.getSonuçResmi();
    }//GEN-LAST:event_Morfo3İtemActionPerformed

    private void Morfo4İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Morfo4İtemActionPerformed
        int[] mask = {0, 1, 0, 1, 1, 1, 0, 1, 0};

        morfolojik = new Morfolojik(SonResim);
        resimLabel.setIcon(new ImageIcon(morfolojik.Closing(mask, 3)));
        SonResim = morfolojik.getSonuçResmi();
    }//GEN-LAST:event_Morfo4İtemActionPerformed

    private void Segme1İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Segme1İtemActionPerformed
        Segmentasyon yeni = new Segmentasyon(SonResim);
        System.out.println(yeni.EsikDegeriHesapla(SonResim));
        //  resimLabel.setIcon(new ImageIcon(yeni.EsikDegeriHesapla(SonResim)));
        //    yeni.EsikDegeriHesapla(SonResim);

    }//GEN-LAST:event_Segme1İtemActionPerformed

    private void Segme2İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Segme2İtemActionPerformed
        Segmentasyon yeni = new Segmentasyon(SonResim);

        resimLabel.setIcon(new ImageIcon(yeni.dörkenar(SonResim)));
        SonResim=yeni.getSonuçResmi();
    }//GEN-LAST:event_Segme2İtemActionPerformed

    private void Segme3İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Segme3İtemActionPerformed
        önislem = new Önİslem(SonResim);
        SonResim = önislem.GriyeCevir();
        Segmentasyon yeni = new Segmentasyon(SonResim);
        resimLabel.setIcon(new ImageIcon(yeni.RenkliResimdeNesneBul(SonResim)));
        SonResim=yeni.getSonuçResmi();
    }//GEN-LAST:event_Segme3İtemActionPerformed

    private void Segme4İtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Segme4İtemActionPerformed
        Segmentasyon yeni = new Segmentasyon(SonResim);
        resimLabel.setIcon(new ImageIcon(yeni.RenkliResimdeNesneBul(SonResim)));
    }//GEN-LAST:event_Segme4İtemActionPerformed
    public void kaydet(String kayitTürü) {
        BufferedImage bufferedImage = SonResim;
        

        try {

            BufferedImage newBufferedImage = new BufferedImage(bufferedImage.getWidth(),
                    bufferedImage.getHeight(), BufferedImage.TYPE_INT_RGB);
            newBufferedImage.createGraphics().drawImage(bufferedImage, 0, 0, Color.WHITE, null);

            ImageIO.write(newBufferedImage, "jpg", new File("d:\\Kayit." + kayitTürü));

            System.out.println("Done");

        } catch (IOException e) {

            e.printStackTrace();

        }
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        kaydet("JPG");

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        kaydet("BMP");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        kaydet("TIF");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        kaydet("PNG");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    public void paint(Graphics g) {
        super.paintComponents(g);
        if (KesmeAktif) {

            int w = Math.abs(önislem.getX1() - önislem.getX2());
            int h = Math.abs(önislem.getY1() - önislem.getY2());

            if (önislem.getX1() < önislem.getX2() && önislem.getY1() > önislem.getY2()) {
                g.drawRect(önislem.getX1(), önislem.getY2(), w, h);
            } else if (önislem.getX1() > önislem.getX2() && önislem.getY2() > önislem.getY1()) {
                g.drawRect(önislem.getX2(), önislem.getY1(), w, h);
            } else if (önislem.getX2() > önislem.getX1() && önislem.getY2() > önislem.getY1()) {
                g.drawRect(önislem.getX1(), önislem.getY1(), w, h);
            } else if (önislem.getX1() > önislem.getX2() && önislem.getY1() > önislem.getY2()) {
                g.drawRect(önislem.getX2(), önislem.getY2(), w, h);
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Filtre1İtem;
    private javax.swing.JMenuItem Filtre2İtem;
    private javax.swing.JMenuItem Filtre3İtem;
    private javax.swing.JMenuItem Filtre4İtem;
    private javax.swing.JMenuItem Filtre5İtem;
    private javax.swing.JMenu FiltreMenü;
    private javax.swing.JCheckBoxMenuItem FiltreRadio;
    private javax.swing.JMenuItem Morfo1İtem;
    private javax.swing.JMenuItem Morfo2İtem;
    private javax.swing.JMenuItem Morfo3İtem;
    private javax.swing.JMenuItem Morfo4İtem;
    private javax.swing.JMenu MorfoMenü;
    private javax.swing.JCheckBoxMenuItem MorfoRadio;
    private javax.swing.JScrollPane ResimScrollPane;
    private javax.swing.JMenuItem Segme1İtem;
    private javax.swing.JMenuItem Segme2İtem;
    private javax.swing.JMenuItem Segme3İtem;
    private javax.swing.JMenuItem Segme4İtem;
    private javax.swing.JCheckBoxMenuItem SegmensatyonRadio;
    private javax.swing.JMenu SegmentMenü;
    private javax.swing.JTextField Xtext;
    private javax.swing.JTextField YText;
    private javax.swing.JButton ZoomOutButton;
    private javax.swing.JButton ZoomİnButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem Önİslem1İtem;
    private javax.swing.JMenuItem Önİslem2İtem;
    private javax.swing.JMenuItem Önİslem3İtem;
    private javax.swing.JMenuItem Önİslem4İtem;
    private javax.swing.JMenuItem Önİslem5İtem;
    private javax.swing.JMenu ÖnİslemMenü;
    private javax.swing.JCheckBoxMenuItem ÖnİslemRadio;
    // End of variables declaration//GEN-END:variables
}
